"""
База данных команд для Windows, Linux и macOS
Расширенная версия с интерактивными сценариями
"""

COMMANDS = {
    "windows": {
        "name": "Windows (PowerShell)",
        "icon": "🪟",
        "commands": [
            # ==================== СИСТЕМА ====================
            {"name": "Get-Process", "command": "Get-Process | Select-Object Name, CPU, WorkingSet -First 20", "description": "Запущенные процессы (топ-20)", "description_en": "Running processes (top 20)", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-Service", "command": "Get-Service | Where-Object Status -EQ 'Running' | Select-Object Name, Status -First 20", "description": "Работающие службы", "description_en": "Running services", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-EventLog", "command": "Get-EventLog -LogName System -Newest 10", "description": "Последние 10 событий", "description_en": "Last 10 events", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-ComputerInfo", "command": "Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, OsArchitecture", "description": "Информация о системе", "description_en": "System information", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-LocalUser", "command": "Get-LocalUser | Select-Object Name, Enabled, LastLogon", "description": "Локальные пользователи", "description_en": "Local users", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-LocalGroup", "command": "Get-LocalGroup", "description": "Локальные группы", "description_en": "Local groups", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-Process (Top CPU)", "command": "Get-Process | Sort-Object CPU -Descending | Select-Object Name, CPU -First 10", "description": "Топ-10 по CPU", "description_en": "Top 10 by CPU", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-Process (Top RAM)", "command": "Get-Process | Sort-Object WorkingSet -Descending | Select-Object Name, WorkingSet -First 10", "description": "Топ-10 по памяти", "description_en": "Top 10 by RAM", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-PSDrive", "command": "Get-PSDrive | Select-Object Name, Root, Used, Free", "description": "Диски и разделы", "description_en": "Drives and partitions", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-Date", "command": "Get-Date -Format \"dd.MM.yyyy HH:mm:ss\"", "description": "Дата и время", "description_en": "Date and time", "category": "Система", "interactive": True, "safe": True},
            {"name": "systeminfo", "command": "systeminfo | Select-String \"OS Name|OS Version|System Type\"", "description": "Подробная информация", "description_en": "Detailed system info", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-HotFix", "command": "Get-HotFix | Select-Object HotFixID, Description, InstalledOn -First 10", "description": "Установленные обновления", "description_en": "Installed updates", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-ScheduledTask", "command": "Get-ScheduledTask | Where-Object State -EQ 'Ready' | Select-Object TaskName -First 15", "description": "Запланированные задачи", "description_en": "Scheduled tasks", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-Counter (CPU)", "command": "Get-Counter '\\Processor(_Total)\\% Processor Time'", "description": "Загрузка процессора", "description_en": "CPU usage", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-CimInstance (BIOS)", "command": "Get-CimInstance Win32_BIOS | Select-Object Manufacturer, Version", "description": "Информация BIOS", "description_en": "BIOS information", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-CimInstance (Video)", "command": "Get-CimInstance Win32_VideoController | Select-Object Name, DriverVersion", "description": "Видеокарта", "description_en": "Video card info", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-Uptime", "command": "(Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUpTime", "description": "Время работы", "description_en": "System uptime", "category": "Система", "interactive": True, "safe": True},
            {"name": "Get-Environment", "command": "Get-ChildItem Env: | Select-Object Name, Value -First 20", "description": "Переменные окружения", "description_en": "Environment variables", "category": "Система", "interactive": True, "safe": True},
            
            # ==================== ФАЙЛЫ ====================
            {"name": "Get-ChildItem", "command": "Get-ChildItem | Select-Object Name, Length, LastWriteTime", "description": "Содержимое директории", "description_en": "Directory contents", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Get-ChildItem (All)", "command": "Get-ChildItem -Recurse -File | Measure-Object", "description": "Подсчёт всех файлов", "description_en": "Count all files", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Get-Content", "command": "Get-Content $PROFILE -Head 20 -ErrorAction SilentlyContinue", "description": "Начало профиля PS", "description_en": "PS profile start", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "New-Item (File)", "command": "New-Item -Path \"test_file.txt\" -ItemType File -Force", "description": "Создать файл", "description_en": "Create file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "New-Item (Folder)", "command": "New-Item -Path \"test_folder\" -ItemType Directory -Force", "description": "Создать папку", "description_en": "Create folder", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Remove-Item", "command": "Remove-Item \"test_file.txt\" -Force -ErrorAction SilentlyContinue", "description": "Удалить тестовый файл", "description_en": "Delete test file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Get-FileHash", "command": "Get-FileHash $PROFILE -Algorithm SHA256 -ErrorAction SilentlyContinue", "description": "Хеш файла", "description_en": "File hash", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Select-String", "command": "Select-String -Path \"*.txt\" -Pattern \"test\" | Select-Object -First 10", "description": "Поиск текста", "description_en": "Search text", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Get-ACL", "command": "Get-ACL . | Select-Object Owner", "description": "Права доступа", "description_en": "Access rights", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Compress-Archive", "command": "Get-ChildItem *.txt | Compress-Archive -DestinationPath \"archive.zip\" -Force", "description": "Создать ZIP", "description_en": "Create ZIP", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Get-FileSize", "command": "Get-ChildItem -File | Measure-Object -Property Length -Sum", "description": "Размер файлов", "description_en": "Files size", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "Get-RecentFiles", "command": "Get-ChildItem | Sort-Object LastWriteTime -Descending | Select-Object Name -First 10", "description": "Последние файлы", "description_en": "Recent files", "category": "Файлы", "interactive": True, "safe": True},
            
            # ==================== СЕТЬ ====================
            {"name": "Test-Connection", "command": "Test-Connection google.com -Count 4 | Select-Object ResponseTime", "description": "Ping до Google", "description_en": "Ping Google", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Get-NetIPAddress", "command": "Get-NetIPAddress | Where-Object AddressFamily -EQ 'IPv4' | Select-Object IPAddress", "description": "IPv4 адреса", "description_en": "IPv4 addresses", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Get-NetTCPConnection", "command": "Get-NetTCPConnection | Where-Object State -EQ 'Established' | Select-Object LocalAddress, RemoteAddress -First 10", "description": "TCP соединения", "description_en": "TCP connections", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Get-NetAdapter", "command": "Get-NetAdapter | Select-Object Name, Status, LinkSpeed", "description": "Сетевые адаптеры", "description_en": "Network adapters", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Get-DnsClient", "command": "Get-DnsClientServerAddress | Where-Object AddressFamily -EQ 2 | Select-Object ServerAddresses", "description": "DNS серверы", "description_en": "DNS servers", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Get-NetRoute", "command": "Get-NetRoute | Where-Object DestinationPrefix -EQ '0.0.0.0/0'", "description": "Таблица маршрутизации", "description_en": "Routing table", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Invoke-WebRequest", "command": "Invoke-WebRequest -Uri \"https://api.ipify.org\" | Select-Object Content", "description": "Внешний IP", "description_en": "External IP", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Test-NetConnection", "command": "Test-NetConnection google.com -Port 443 | Select-Object TcpTestSucceeded", "description": "Проверка порта 443", "description_en": "Check port 443", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "Get-NetFirewallRule", "command": "Get-NetFirewallRule | Where-Object Enabled -EQ True | Select-Object DisplayName -First 15", "description": "Правила фаервола", "description_en": "Firewall rules", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "ipconfig", "command": "ipconfig | Select-String \"IPv4|Gateway|DNS\"", "description": "IP конфигурация", "description_en": "IP configuration", "category": "Сеть", "interactive": True, "safe": True},
            
            # ==================== НАВИГАЦИЯ ====================
            {"name": "Get-Location", "command": "Get-Location", "description": "Текущая директория", "description_en": "Current directory", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "Push-Location", "command": "Push-Location $env:TEMP; Get-Location; Pop-Location", "description": "Сменить директорию", "description_en": "Change directory", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "Resolve-Path", "command": "Resolve-Path ~", "description": "Домашняя папка", "description_en": "Home folder", "category": "Навигация", "interactive": True, "safe": True},
            
            # ==================== ПРОЦЕССЫ ====================
            {"name": "Start-Process", "command": "Start-Process notepad", "description": "Запустить Блокнот", "description_en": "Launch Notepad", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "Stop-Process", "command": "Get-Process notepad -ErrorAction SilentlyContinue | Stop-Process -Force", "description": "Закрыть Блокнот", "description_en": "Close Notepad", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "Get-Process (explorer)", "command": "Get-Process explorer | Select-Object Name, Id, StartTime", "description": "О проводнике", "description_en": "Explorer info", "category": "Процессы", "interactive": True, "safe": True},
            
            # ==================== РЕЕСТР ====================
            {"name": "Get-ItemProperty (Run)", "command": "Get-ItemProperty \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\"", "description": "Автозагрузка", "description_en": "Autorun programs", "category": "Реестр", "interactive": True, "safe": True},
            {"name": "Get-ChildItem (Registry)", "command": "Get-ChildItem HKCU:\\Software\\Microsoft | Select-Object Name -First 15", "description": "Разделы реестра", "description_en": "Registry keys", "category": "Реестр", "interactive": True, "safe": True},
            
            # ==================== ПРОЧЕЕ ====================
            {"name": "Get-Command", "command": "Get-Command -Module Microsoft.PowerShell.Utility | Select-Object Name -First 20", "description": "Доступные команды", "description_en": "Available commands", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "Get-Help", "command": "Get-Help Get-Process -Examples", "description": "Примеры Get-Process", "description_en": "Get-Process examples", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "Measure-Command", "command": "Measure-Command { Get-ChildItem } | Select-Object TotalMilliseconds", "description": "Время выполнения", "description_en": "Execution time", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "Write-Host", "command": "Write-Host \"Hello!\" -ForegroundColor Green", "description": "Цветной текст", "description_en": "Colored text", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "Clear-Host", "command": "Clear-Host", "description": "Очистить консоль", "description_en": "Clear console", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "Get-Random", "command": "Get-Random -Minimum 1 -Maximum 100", "description": "Случайное число", "description_en": "Random number", "category": "Прочее", "interactive": True, "safe": True},
            
            # ==================== ДОМЕН/LDAP ====================
            {"name": "Get-ADDomain", "command": "Get-ADDomain | Select-Object DomainName, Forest, DomainMode", "description": "Информация о домене", "description_en": "Domain information", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADDomainController", "command": "Get-ADDomainController | Select-Object HostName, IPv4Address, Site", "description": "Контроллеры домена", "description_en": "Domain controllers", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADUser (Domain)", "command": "Get-ADUser -Filter * -Properties Department | Select-Object Name, SamAccountName, Department -First 20", "description": "Пользователи домена", "description_en": "Domain users", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADGroup", "command": "Get-ADGroup -Filter * | Select-Object Name, GroupScope, GroupCategory -First 20", "description": "Группы домена", "description_en": "Domain groups", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADComputer", "command": "Get-ADComputer -Filter * | Select-Object Name, OperatingSystem, LastLogonDate -First 15", "description": "Компьютеры домена", "description_en": "Domain computers", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Test-ComputerSecureChannel", "command": "Test-ComputerSecureChannel -Verbose", "description": "Проверка канала домена", "description_en": "Domain channel test", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADOrganizationalUnit", "command": "Get-ADOrganizationalUnit -Filter * | Select-Object DistinguishedName, ProtectedFromAccidentalDeletion -First 15", "description": "Подразделения домена", "description_en": "Domain OUs", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADUser (Logged On)", "command": "Get-ADUser -Filter {Enabled -eq $true} -Properties LastLogonDate | Where-Object LastLogonDate -lt (Get-Date).AddDays(-90) | Select-Object Name, LastLogonDate -First 15", "description": "Неактивные пользователи", "description_en": "Inactive users", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADFineGrainedPasswordPolicy", "command": "Get-ADFineGrainedPasswordPolicy -Filter * | Select-Object Name, Precedence, MinPasswordLength", "description": "Политики паролей", "description_en": "Password policies", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "netdom (Trusted Domains)", "command": "netdom trust %USERDOMAIN% /Domain: /Enum:Trusted | Select-String \"Trusted Domain\"", "description": "Доверительные отношения", "description_en": "Trust relationships", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADDefaultDomainPasswordPolicy", "command": "Get-ADDefaultDomainPasswordPolicy | Select-Object MinPasswordLength, PasswordComplexity, MaxPasswordAge", "description": "Политика паролей домена", "description_en": "Domain password policy", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "Get-ADReplicationSite", "command": "Get-ADReplicationSite -Filter * | Select-Object Name, SitesLinkedWith", "description": "Репликация домена", "description_en": "Domain replication", "category": "Домен/LDAP", "interactive": True, "safe": True},
        ]
    },
    
    "linux": {
        "name": "Linux (bash)",
        "icon": "🐧",
        "commands": [
            # ==================== СИСТЕМА ====================
            {"name": "ps aux", "command": "ps aux --sort=-%cpu | head -20", "description": "Процессы (по CPU)", "description_en": "Processes (by CPU)", "category": "Система", "interactive": True, "safe": True},
            {"name": "top", "command": "top -bn1 | head -25", "description": "Топ процессов", "description_en": "Top processes", "category": "Система", "interactive": True, "safe": True},
            {"name": "htop", "command": "htop -b -n 1 | head -30", "description": "Интерактивный top", "description_en": "Interactive top", "category": "Система", "interactive": True, "safe": True},
            {"name": "free -h", "command": "free -h", "description": "Память", "description_en": "Memory usage", "category": "Система", "interactive": True, "safe": True},
            {"name": "vmstat", "command": "vmstat -s", "description": "Статистика памяти", "description_en": "Memory statistics", "category": "Система", "interactive": True, "safe": True},
            {"name": "df -h", "command": "df -h", "description": "Дисковое пространство", "description_en": "Disk space", "category": "Система", "interactive": True, "safe": True},
            {"name": "du -sh", "command": "du -sh * 2>/dev/null | sort -hr | head -15", "description": "Размер папок", "description_en": "Folder sizes", "category": "Система", "interactive": True, "safe": True},
            {"name": "uname -a", "command": "uname -a", "description": "Информация о ядре", "description_en": "Kernel info", "category": "Система", "interactive": True, "safe": True},
            {"name": "hostnamectl", "command": "hostnamectl", "description": "Информация о хосте", "description_en": "Host information", "category": "Система", "interactive": True, "safe": True},
            {"name": "whoami", "command": "whoami", "description": "Текущий пользователь", "description_en": "Current user", "category": "Система", "interactive": True, "safe": True},
            {"name": "id", "command": "id", "description": "ID пользователя", "description_en": "User ID", "category": "Система", "interactive": True, "safe": True},
            {"name": "uptime", "command": "uptime -p", "description": "Время работы", "description_en": "Uptime", "category": "Система", "interactive": True, "safe": True},
            {"name": "w", "command": "w", "description": "Кто в системе", "description_en": "Who is logged in", "category": "Система", "interactive": True, "safe": True},
            {"name": "last", "command": "last -10", "description": "Последние входы", "description_en": "Last logins", "category": "Система", "interactive": True, "safe": True},
            {"name": "systemctl status", "command": "systemctl --type=service --state=running | head -20", "description": "Работающие службы", "description_en": "Running services", "category": "Система", "interactive": True, "safe": True},
            {"name": "journalctl", "command": "journalctl -b | tail -30", "description": "Логи загрузки", "description_en": "Boot logs", "category": "Система", "interactive": True, "safe": True},
            {"name": "dmesg", "command": "dmesg | tail -30", "description": "Сообщения ядра", "description_en": "Kernel messages", "category": "Система", "interactive": True, "safe": True},
            {"name": "lscpu", "command": "lscpu | grep -E \"Model name|CPU\\(s\\)|Architecture\"", "description": "Информация о CPU", "description_en": "CPU information", "category": "Система", "interactive": True, "safe": True},
            {"name": "lsblk", "command": "lsblk", "description": "Блочные устройства", "description_en": "Block devices", "category": "Система", "interactive": True, "safe": True},
            {"name": "lspci", "command": "lspci | head -20", "description": "PCI устройства", "description_en": "PCI devices", "category": "Система", "interactive": True, "safe": True},
            {"name": "lsusb", "command": "lsusb", "description": "USB устройства", "description_en": "USB devices", "category": "Система", "interactive": True, "safe": True},
            {"name": "getconf", "command": "getconf LONG_BIT", "description": "Разрядность системы", "description_en": "System bits", "category": "Система", "interactive": True, "safe": True},
            {"name": "cat /etc/os-release", "command": "cat /etc/os-release", "description": "Версия ОС", "description_en": "OS version", "category": "Система", "interactive": True, "safe": True},
            {"name": "cat /proc/meminfo", "command": "cat /proc/meminfo | head -15", "description": "Детали памяти", "description_en": "Memory details", "category": "Система", "interactive": True, "safe": True},
            
            # ==================== ФАЙЛЫ ====================
            {"name": "ls -la", "command": "ls -la", "description": "Содержимое директории", "description_en": "Directory listing", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "ls -lh", "command": "ls -lh", "description": "С размерами", "description_en": "With sizes", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "tree", "command": "tree -L 2 -d 2>/dev/null || find . -maxdepth 2 -type d", "description": "Дерево папок", "description_en": "Folder tree", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "cat", "command": "cat /etc/passwd | head -10", "description": "Пользователи системы", "description_en": "System users", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "head", "command": "head -20 /var/log/syslog 2>/dev/null || journalctl -b | head -20", "description": "Начало файла логов", "description_en": "Log file start", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "tail", "command": "tail -20 /var/log/syslog 2>/dev/null || journalctl -b | tail -20", "description": "Конец файла логов", "description_en": "Log file end", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "touch", "command": "touch test_file.txt && ls -la test_file.txt", "description": "Создать файл", "description_en": "Create file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "mkdir", "command": "mkdir -p test_dir && ls -la | grep test_dir", "description": "Создать папку", "description_en": "Create folder", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "rm", "command": "rm -f test_file.txt && echo \"File removed\"", "description": "Удалить файл", "description_en": "Delete file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "cp", "command": "cp /etc/hostname ./hostname_backup && cat hostname_backup", "description": "Копировать файл", "description_en": "Copy file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "mv", "command": "mv hostname_backup hostname_renamed && ls hostname_*", "description": "Переименовать", "description_en": "Rename file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "grep", "command": "grep -r \"root\" /etc/passwd", "description": "Поиск текста", "description_en": "Search text", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "find", "command": "find . -maxdepth 2 -name \"*.txt\" 2>/dev/null", "description": "Поиск файлов", "description_en": "Find files", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "locate", "command": "locate passwd | head -10 2>/dev/null || echo \"locate not available\"", "description": "Быстрый поиск", "description_en": "Fast search", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "chmod", "command": "chmod 755 test_dir && ls -la | grep test_dir", "description": "Изменить права", "description_en": "Change permissions", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "chown", "command": "stat -c '%U:%G %n' * | head -10", "description": "Владельцы файлов", "description_en": "File owners", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "tar", "command": "tar -czf test_archive.tar.gz test_dir 2>/dev/null && ls -la *.tar.gz", "description": "Создать архив", "description_en": "Create archive", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "zip", "command": "zip -r test_archive.zip test_dir 2>/dev/null && ls -la *.zip", "description": "Создать ZIP", "description_en": "Create ZIP", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "file", "command": "file /bin/bash", "description": "Тип файла", "description_en": "File type", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "stat", "command": "stat /etc/passwd", "description": "Статистика файла", "description_en": "File statistics", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "ln -s", "command": "ln -sf /etc/hostname ./hostname_link && ls -la hostname_link", "description": "Символическая ссылка", "description_en": "Symbolic link", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "wc -l", "command": "wc -l /etc/passwd", "description": "Количество строк", "description_en": "Line count", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "sort", "command": "cat /etc/passwd | cut -d: -f1 | sort", "description": "Сортировка", "description_en": "Sort output", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "uniq", "command": "ps aux | awk '{print $1}' | sort | uniq -c | sort -rn | head -10", "description": "Уникальные значения", "description_en": "Unique values", "category": "Файлы", "interactive": True, "safe": True},
            
            # ==================== СЕТЬ ====================
            {"name": "ping", "command": "ping -c 4 google.com", "description": "Ping до Google", "description_en": "Ping Google", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "ip addr", "command": "ip addr show | grep -E \"inet |link/\"", "description": "IP адреса", "description_en": "IP addresses", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "ifconfig", "command": "ifconfig 2>/dev/null || ip addr", "description": "Сетевые интерфейсы", "description_en": "Network interfaces", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "ss -tulpn", "command": "ss -tulpn | head -20", "description": "Открытые порты", "description_en": "Open ports", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "netstat", "command": "netstat -tulpn 2>/dev/null | head -20 || ss -tulpn", "description": "Сетевые соединения", "description_en": "Network connections", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "curl", "command": "curl -s -I https://example.com | head -10", "description": "HTTP запрос", "description_en": "HTTP request", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "curl (IP)", "command": "curl -s https://api.ipify.org", "description": "Внешний IP", "description_en": "External IP", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "wget", "command": "wget --spider https://example.com 2>&1 | head -5", "description": "Проверка URL", "description_en": "Check URL", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "dig", "command": "dig google.com +short 2>/dev/null || nslookup google.com", "description": "DNS запрос", "description_en": "DNS query", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "nslookup", "command": "nslookup google.com 2>/dev/null | head -10", "description": "DNS информация", "description_en": "DNS information", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "host", "command": "host google.com 2>/dev/null", "description": "DNS хост", "description_en": "DNS host", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "cat /etc/hosts", "command": "cat /etc/hosts", "description": "Файл hosts", "description_en": "Hosts file", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "cat /etc/resolv.conf", "command": "cat /etc/resolv.conf", "description": "DNS конфигурация", "description_en": "DNS config", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "route", "command": "route -n 2>/dev/null || ip route", "description": "Таблица маршрутов", "description_en": "Routing table", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "traceroute", "command": "traceroute -m 10 google.com 2>/dev/null | head -15 || tracepath google.com 2>/dev/null | head -15", "description": "Трассировка", "description_en": "Traceroute", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "mtr", "command": "mtr -c 5 -r google.com 2>/dev/null | head -20", "description": "Диагностика сети", "description_en": "Network diagnostic", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "arp", "command": "arp -a 2>/dev/null | head -10", "description": "ARP таблица", "description_en": "ARP table", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "iptables", "command": "iptables -L -n 2>/dev/null | head -20 || echo \"iptables requires root\"", "description": "Правила фаервола", "description_en": "Firewall rules", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "iwconfig", "command": "iwconfig 2>/dev/null || iw dev 2>/dev/null | head -20", "description": "WiFi информация", "description_en": "WiFi information", "category": "Сеть", "interactive": True, "safe": True},
            
            # ==================== НАВИГАЦИЯ ====================
            {"name": "pwd", "command": "pwd", "description": "Текущая директория", "description_en": "Current directory", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "cd ~", "command": "cd ~ && pwd", "description": "Домашняя папка", "description_en": "Home folder", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "cd -", "command": "cd - 2>/dev/null || pwd", "description": "Предыдущая папка", "description_en": "Previous folder", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "dirs", "command": "dirs -v", "description": "Стек директорий", "description_en": "Directory stack", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "realpath", "command": "realpath .", "description": "Абсолютный путь", "description_en": "Absolute path", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "readlink", "command": "readlink -f .", "description": "Канонический путь", "description_en": "Canonical path", "category": "Навигация", "interactive": True, "safe": True},
            
            # ==================== ПРОЦЕССЫ ====================
            {"name": "pgrep", "command": "pgrep -a bash | head -10", "description": "Найти процесс", "description_en": "Find process", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "pkill", "command": "echo \"Use with caution - would kill processes\"", "description": "Завершить процесс", "description_en": "Kill process", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "nice", "command": "nice -n 10 echo \"Priority test\"", "description": "Приоритет процесса", "description_en": "Process priority", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "renice", "command": "renice -n 10 $$ 2>/dev/null; echo \"Current PID: $$\"", "description": "Изменить приоритет", "description_en": "Change priority", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "nohup", "command": "nohup echo \"Test\" &", "description": "Фоновый процесс", "description_en": "Background process", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "jobs", "command": "jobs -l", "description": "Фоновые задачи", "description_en": "Background jobs", "category": "Процессы", "interactive": True, "safe": True},
            
            # ==================== ПРОЧЕЕ ====================
            {"name": "date", "command": "date '+%d.%m.%Y %H:%M:%S'", "description": "Дата и время", "description_en": "Date and time", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "cal", "command": "cal", "description": "Календарь", "description_en": "Calendar", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "alias", "command": "alias | head -15", "description": "Алиасы", "description_en": "Aliases", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "env", "command": "env | sort | head -20", "description": "Переменные окружения", "description_en": "Environment variables", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "echo", "command": "echo \"Hello from Linux!\"", "description": "Вывод текста", "description_en": "Output text", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "printf", "command": "printf \"Formatted: %s %d\\n\" \"Number\" 42", "description": "Форматированный вывод", "description_en": "Formatted output", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "seq", "command": "seq 1 10", "description": "Последовательность", "description_en": "Sequence", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "RANDOM", "command": "echo $RANDOM", "description": "Случайное число", "description_en": "Random number", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "history", "command": "history | tail -15", "description": "История команд", "description_en": "Command history", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "which", "command": "which bash python3 ls", "description": "Путь к команде", "description_en": "Command path", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "type", "command": "type cd ls echo", "description": "Тип команды", "description_en": "Command type", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "man", "command": "man -w ls 2>/dev/null || echo \"Manual page location\"", "description": "Страница man", "description_en": "Man page", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "apropos", "command": "apropos \"search\" 2>/dev/null | head -10", "description": "Поиск в man", "description_en": "Man search", "category": "Прочее", "interactive": True, "safe": True},
            
            # ==================== ДОМЕН/LDAP ====================
            {"name": "ldapsearch (Base)", "command": "ldapsearch -x -H ldap://localhost -b \"dc=example,dc=com\" -s base \"(objectClass=*)\" 2>/dev/null || echo \"ldapsearch: Install openldap-utils\"", "description": "Базовый LDAP запрос", "description_en": "Basic LDAP query", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapsearch (Users)", "command": "ldapsearch -x -H ldap://localhost -b \"dc=example,dc=com\" \"(objectClass=person)\" cn mail 2>/dev/null | head -30", "description": "Пользователи LDAP", "description_en": "LDAP users", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapsearch (Groups)", "command": "ldapsearch -x -H ldap://localhost -b \"dc=example,dc=com\" \"(objectClass=groupOfNames)\" cn member 2>/dev/null | head -30", "description": "Группы LDAP", "description_en": "LDAP groups", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapsearch (TLS)", "command": "ldapsearch -x -ZZ -H ldaps://localhost -b \"dc=example,dc=com\" \"(objectClass=*)\" 2>/dev/null | head -20", "description": "LDAP через TLS", "description_en": "LDAP over TLS", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapwhoami", "command": "ldapwhoami -x -H ldap://localhost 2>/dev/null || echo \"ldapwhoami: Install openldap-utils\"", "description": "Проверка аутентификации", "description_en": "Auth check", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapmodify (Template)", "command": "echo \"ldapmodify -x -H ldap://localhost -D 'cn=admin,dc=example,dc=com' -W\" && echo \"Requires interactive password\"", "description": "Изменение LDAP (шаблон)", "description_en": "LDAP modify (template)", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapdelete (Template)", "command": "echo \"ldapdelete -x -H ldap://localhost -D 'cn=admin,dc=example,dc=com' -W 'dn'\" && echo \"Requires interactive password\"", "description": "Удаление LDAP (шаблон)", "description_en": "LDAP delete (template)", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "getent (passwd)", "command": "getent passwd | head -10", "description": "Пользователи из LDAP/NIS", "description_en": "Users from LDAP/NIS", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "getent (group)", "command": "getent group | head -10", "description": "Группы из LDAP/NIS", "description_en": "Groups from LDAP/NIS", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "getent (hosts)", "command": "getent hosts localhost", "description": "Хосты из DNS/NIS", "description_en": "Hosts from DNS/NIS", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "id (LDAP user)", "command": "id username 2>/dev/null || echo \"id: Check LDAP user exists\"", "description": "ID пользователя", "description_en": "User ID", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "realm (Discover)", "command": "realm discover 2>/dev/null || echo \"realm: Install realmd package\"", "description": "Обнаружение домена", "description_en": "Domain discovery", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "realm (List)", "command": "realm list 2>/dev/null || echo \"realm: Not joined to domain\"", "description": "Информация о домене", "description_en": "Domain information", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "sssd (Status)", "command": "systemctl status sssd 2>/dev/null | head -15 || echo \"sssd: Service not found\"", "description": "Статус SSSD", "description_en": "SSSD status", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "cat /etc/ldap.conf", "command": "cat /etc/ldap.conf 2>/dev/null || cat /etc/pam_ldap.conf 2>/dev/null || echo \"LDAP config not found\"", "description": "LDAP конфигурация", "description_en": "LDAP configuration", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "cat /etc/nsswitch.conf", "command": "grep -E \"passwd|group|hosts\" /etc/nsswitch.conf", "description": "NSS конфигурация", "description_en": "NSS configuration", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "net ads (Info)", "command": "net ads info -k 2>/dev/null || echo \"net: Install samba-common-tools\"", "description": "Информация о Active Directory", "description_en": "AD information", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "net ads (Join)", "command": "echo \"net ads join -U administrator\" && echo \"Requires interactive password\"", "description": "Присоединение к домену (шаблон)", "description_en": "Join domain (template)", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "kinit (Kerberos)", "command": "echo \"kinit username@DOMAIN.COM\" && echo \"Requires interactive password\"", "description": "Kerberos аутентификация (шаблон)", "description_en": "Kerberos auth (template)", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "klist (Tickets)", "command": "klist 2>/dev/null || echo \"klist: No Kerberos tickets\"", "description": "Kerberos билеты", "description_en": "Kerberos tickets", "category": "Домен/LDAP", "interactive": True, "safe": True},
        ]
    },
    
    "macos": {
        "name": "macOS (Terminal)",
        "icon": "🍎",
        "commands": [
            # ==================== СИСТЕМА ====================
            {"name": "ps aux", "command": "ps aux --sort=-%cpu | head -20", "description": "Процессы (по CPU)", "description_en": "Processes (by CPU)", "category": "Система", "interactive": True, "safe": True},
            {"name": "top", "command": "top -l 1 | head -30", "description": "Топ процессов", "description_en": "Top processes", "category": "Система", "interactive": True, "safe": True},
            {"name": "vm_stat", "command": "vm_stat", "description": "Виртуальная память", "description_en": "Virtual memory", "category": "Система", "interactive": True, "safe": True},
            {"name": "sysctl hw.memsize", "command": "sysctl hw.memsize", "description": "Объём памяти", "description_en": "Memory size", "category": "Система", "interactive": True, "safe": True},
            {"name": "df -h", "command": "df -h", "description": "Дисковое пространство", "description_en": "Disk space", "category": "Система", "interactive": True, "safe": True},
            {"name": "du -sh", "command": "du -sh * 2>/dev/null | sort -hr | head -15", "description": "Размер папок", "description_en": "Folder sizes", "category": "Система", "interactive": True, "safe": True},
            {"name": "sw_vers", "command": "sw_vers", "description": "Версия macOS", "description_en": "macOS version", "category": "Система", "interactive": True, "safe": True},
            {"name": "uname -a", "command": "uname -a", "description": "Информация о ядре", "description_en": "Kernel info", "category": "Система", "interactive": True, "safe": True},
            {"name": "hostname", "command": "hostname", "description": "Имя хоста", "description_en": "Hostname", "category": "Система", "interactive": True, "safe": True},
            {"name": "whoami", "command": "whoami", "description": "Текущий пользователь", "description_en": "Current user", "category": "Система", "interactive": True, "safe": True},
            {"name": "id", "command": "id", "description": "ID пользователя", "description_en": "User ID", "category": "Система", "interactive": True, "safe": True},
            {"name": "uptime", "command": "uptime", "description": "Время работы", "description_en": "Uptime", "category": "Система", "interactive": True, "safe": True},
            {"name": "w", "command": "w", "description": "Кто в системе", "description_en": "Who is logged in", "category": "Система", "interactive": True, "safe": True},
            {"name": "last", "command": "last -10", "description": "Последние входы", "description_en": "Last logins", "category": "Система", "interactive": True, "safe": True},
            {"name": "sysctl machdep.cpu", "command": "sysctl machdep.cpu.brand_string", "description": "Информация о CPU", "description_en": "CPU information", "category": "Система", "interactive": True, "safe": True},
            {"name": "system_profiler", "command": "system_profiler SPHardwareDataType | head -15", "description": "Информация о hardware", "description_en": "Hardware information", "category": "Система", "interactive": True, "safe": True},
            {"name": "ioreg", "command": "ioreg -c IOPlatformExpertDevice | grep \"board-id\\|model\"", "description": "Информация о плате", "description_en": "Board information", "category": "Система", "interactive": True, "safe": True},
            {"name": "diskutil list", "command": "diskutil list", "description": "Диски", "description_en": "Disks", "category": "Система", "interactive": True, "safe": True},
            {"name": "systemsetup", "command": "systemsetup -gettimezone", "description": "Часовой пояс", "description_en": "Timezone", "category": "Система", "interactive": True, "safe": True},
            {"name": "pmset", "command": "pmset -g", "description": "Настройки питания", "description_en": "Power settings", "category": "Система", "interactive": True, "safe": True},
            {"name": "kextstat", "command": "kextstat | head -20", "description": "Загруженные кексты", "description_en": "Loaded kexts", "category": "Система", "interactive": True, "safe": True},
            
            # ==================== ФАЙЛЫ ====================
            {"name": "ls -la", "command": "ls -la", "description": "Содержимое директории", "description_en": "Directory listing", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "ls -lO", "command": "ls -lO", "description": "С флагами", "description_en": "With flags", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "cat", "command": "cat /etc/passwd | head -10", "description": "Пользователи", "description_en": "Users", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "less", "command": "less /etc/passwd", "description": "Просмотр файла", "description_en": "View file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "touch", "command": "touch test_file.txt && ls -la test_file.txt", "description": "Создать файл", "description_en": "Create file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "mkdir", "command": "mkdir -p test_dir && ls -la | grep test_dir", "description": "Создать папку", "description_en": "Create folder", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "rm", "command": "rm -f test_file.txt && echo \"Removed\"", "description": "Удалить файл", "description_en": "Delete file", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "cp", "command": "cp /etc/hostname ./hostname_backup 2>/dev/null || cp /etc/hostid ./hostname_backup", "description": "Копировать", "description_en": "Copy", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "mv", "command": "mv hostname_backup hostname_renamed 2>/dev/null; ls hostname_* 2>/dev/null", "description": "Переименовать", "description_en": "Rename", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "grep", "command": "grep -r \"root\" /etc/passwd", "description": "Поиск текста", "description_en": "Search text", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "find", "command": "find . -maxdepth 2 -name \"*.txt\" 2>/dev/null", "description": "Поиск файлов", "description_en": "Find files", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "mdfind", "command": "mdfind \"com.apple.finder\" | head -10", "description": "Spotlight поиск", "description_en": "Spotlight search", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "mdls", "command": "mdls -name kMDItemContentTypeTree /Applications 2>/dev/null | head -10", "description": "Spotlight метаданные", "description_en": "Spotlight metadata", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "xattr", "command": "xattr -l /Applications 2>/dev/null | head -10", "description": "Расширенные атрибуты", "description_en": "Extended attributes", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "chmod", "command": "chmod 755 test_dir && ls -la | grep test_dir", "description": "Изменить права", "description_en": "Change permissions", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "chflags", "command": "chflags -h hidden test_dir 2>/dev/null; ls -lO | grep test_dir", "description": "Флаги файла", "description_en": "File flags", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "tar", "command": "tar -czf test_archive.tar.gz test_dir 2>/dev/null && ls -la *.tar.gz", "description": "Создать архив", "description_en": "Create archive", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "zip", "command": "zip -r test_archive.zip test_dir 2>/dev/null && ls -la *.zip", "description": "Создать ZIP", "description_en": "Create ZIP", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "open", "command": "open .", "description": "Открыть в Finder", "description_en": "Open in Finder", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "qlmanage", "command": "qlmanage -p /Applications 2>&1 | head -5", "description": "Quick Look", "description_en": "Quick Look", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "file", "command": "file /bin/bash", "description": "Тип файла", "description_en": "File type", "category": "Файлы", "interactive": True, "safe": True},
            {"name": "stat", "command": "stat /etc/passwd", "description": "Статистика файла", "description_en": "File statistics", "category": "Файлы", "interactive": True, "safe": True},
            
            # ==================== СЕТЬ ====================
            {"name": "ping", "command": "ping -c 4 google.com", "description": "Ping до Google", "description_en": "Ping Google", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "ifconfig", "command": "ifconfig | grep -E \"inet |ether\"", "description": "Сетевые интерфейсы", "description_en": "Network interfaces", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "ipconfig getifaddr", "command": "ipconfig getifaddr en0", "description": "IP адрес Wi-Fi", "description_en": "WiFi IP address", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "netstat", "command": "netstat -an | head -50", "description": "Сетевые соединения", "description_en": "Network connections", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "lsof -i", "command": "lsof -i -n | head -30", "description": "Открытые соединения", "description_en": "Open connections", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "curl", "command": "curl -s -I https://example.com | head -10", "description": "HTTP запрос", "description_en": "HTTP request", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "curl (IP)", "command": "curl -s https://api.ipify.org", "description": "Внешний IP", "description_en": "External IP", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "networksetup", "command": "networksetup -listallhardwareports", "description": "Сетевые устройства", "description_en": "Network devices", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "scutil", "command": "scutil --dns | head -30", "description": "DNS конфигурация", "description_en": "DNS configuration", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "dig", "command": "dig google.com +short", "description": "DNS запрос", "description_en": "DNS query", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "nslookup", "command": "nslookup google.com", "description": "DNS информация", "description_en": "DNS information", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "traceroute", "command": "traceroute -m 10 google.com | head -15", "description": "Трассировка", "description_en": "Traceroute", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "arp", "command": "arp -a | head -10", "description": "ARP таблица", "description_en": "ARP table", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "nettop", "command": "nettop -J bytes_received,bytes_sent -m TCP -l 1 -t 1 2>/dev/null | head -20", "description": "Сетевой трафик", "description_en": "Network traffic", "category": "Сеть", "interactive": True, "safe": True},
            {"name": "airport", "command": "/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I 2>/dev/null", "description": "WiFi информация", "description_en": "WiFi information", "category": "Сеть", "interactive": True, "safe": True},
            
            # ==================== НАВИГАЦИЯ ====================
            {"name": "pwd", "command": "pwd", "description": "Текущая директория", "description_en": "Current directory", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "cd ~", "command": "cd ~ && pwd", "description": "Домашняя папка", "description_en": "Home folder", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "cd -", "command": "cd - 2>/dev/null || pwd", "description": "Предыдущая папка", "description_en": "Previous folder", "category": "Навигация", "interactive": True, "safe": True},
            {"name": "realpath", "command": "realpath . 2>/dev/null || pwd -P", "description": "Абсолютный путь", "description_en": "Absolute path", "category": "Навигация", "interactive": True, "safe": True},
            
            # ==================== ПРОЦЕССЫ ====================
            {"name": "pgrep", "command": "pgrep -a Finder | head -5", "description": "Найти процесс", "description_en": "Find process", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "killall", "command": "killall -0 Finder 2>/dev/null && echo \"Finder is running\"", "description": "Проверить процесс", "description_en": "Check process", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "launchctl list", "command": "launchctl list | head -30", "description": "Launchd сервисы", "description_en": "Launchd services", "category": "Процессы", "interactive": True, "safe": True},
            {"name": "osascript", "command": "osascript -e 'tell application \"Finder\" to name of folders of desktop' 2>/dev/null", "description": "AppleScript команда", "description_en": "AppleScript command", "category": "Процессы", "interactive": True, "safe": True},
            
            # ==================== ПРОЧЕЕ ====================
            {"name": "date", "command": "date '+%d.%m.%Y %H:%M:%S'", "description": "Дата и время", "description_en": "Date and time", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "cal", "command": "cal", "description": "Календарь", "description_en": "Calendar", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "say", "command": "say \"Hello from macOS\"", "description": "Синтез речи", "description_en": "Text to speech", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "alias", "command": "alias | head -15", "description": "Алиасы", "description_en": "Aliases", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "env", "command": "env | sort | head -20", "description": "Переменные окружения", "description_en": "Environment variables", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "echo", "command": "echo \"Hello from macOS!\"", "description": "Вывод текста", "description_en": "Output text", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "history", "command": "history | tail -15", "description": "История команд", "description_en": "Command history", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "which", "command": "which bash python3 ls", "description": "Путь к команде", "description_en": "Command path", "category": "Прочее", "interactive": True, "safe": True},
            {"name": "man", "command": "man -w ls 2>/dev/null || echo \"Man page\"", "description": "Страница man", "description_en": "Man page", "category": "Прочее", "interactive": True, "safe": True},
            
            # ==================== ДОМЕН/LDAP ====================
            {"name": "ldapsearch (Base)", "command": "ldapsearch -x -H ldap://localhost -b \"dc=example,dc=com\" -s base \"(objectClass=*)\" 2>/dev/null || echo \"ldapsearch: Install openldap\"", "description": "Базовый LDAP запрос", "description_en": "Basic LDAP query", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapsearch (Users)", "command": "ldapsearch -x -H ldap://localhost -b \"dc=example,dc=com\" \"(objectClass=person)\" cn mail 2>/dev/null | head -30", "description": "Пользователи LDAP", "description_en": "LDAP users", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapsearch (Groups)", "command": "ldapsearch -x -H ldap://localhost -b \"dc=example,dc=com\" \"(objectClass=groupOfNames)\" cn member 2>/dev/null | head -30", "description": "Группы LDAP", "description_en": "LDAP groups", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapsearch (TLS)", "command": "ldapsearch -x -ZZ -H ldaps://localhost -b \"dc=example,dc=com\" \"(objectClass=*)\" 2>/dev/null | head -20", "description": "LDAP через TLS", "description_en": "LDAP over TLS", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapwhoami", "command": "ldapwhoami -x -H ldap://localhost 2>/dev/null || echo \"ldapwhoami: Install openldap\"", "description": "Проверка аутентификации", "description_en": "Auth check", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "id (LDAP user)", "command": "id username 2>/dev/null || echo \"id: Check LDAP user exists\"", "description": "ID пользователя", "description_en": "User ID", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dscl (List Users)", "command": "dscl . -list /Users | grep -v \"_\\|root\\|daemon\" | head -15", "description": "Пользователи macOS", "description_en": "macOS users", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dscl (Read User)", "command": "dscl . -read /Users/username 2>/dev/null | head -20 || echo \"dscl: User not found\"", "description": "Информация о пользователе", "description_en": "User information", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dscl (List Groups)", "command": "dscl . -list /Groups | head -20", "description": "Группы macOS", "description_en": "macOS groups", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dscl (Group Members)", "command": "dscl . -read /Groups/admin GroupMembership 2>/dev/null", "description": "Члены группы", "description_en": "Group members", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dscacheutil (Users)", "command": "dscacheutil -q user -a name username 2>/dev/null | head -10", "description": "Кэш пользователей", "description_en": "User cache", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dscacheutil (Groups)", "command": "dscacheutil -q group -a name admin 2>/dev/null | head -10", "description": "Кэш групп", "description_en": "Group cache", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dsconfigad (Status)", "command": "dsconfigad -show 2>/dev/null | head -20 || echo \"Not joined to AD\"", "description": "Статус Active Directory", "description_en": "AD status", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dsconfigad (Join)", "command": "echo \"dsconfigad -add domain.com username -username username\" && echo \"Requires admin password\"", "description": "Присоединение к AD (шаблон)", "description_en": "Join AD (template)", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "dsconfigad (Leave)", "command": "echo \"dsconfigad -remove\" && echo \"Requires admin password\"", "description": "Выход из AD (шаблон)", "description_en": "Leave AD (template)", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "kinit (Kerberos)", "command": "echo \"kinit username@DOMAIN.COM\" && echo \"Requires interactive password\"", "description": "Kerberos аутентификация (шаблон)", "description_en": "Kerberos auth (template)", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "klist (Tickets)", "command": "klist 2>/dev/null || echo \"klist: No Kerberos tickets\"", "description": "Kerberos билеты", "description_en": "Kerberos tickets", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "security (Find AD)", "command": "security find-certificate -c \"Active Directory\" 2>/dev/null | head -10 || echo \"No AD certificates\"", "description": "AD сертификаты", "description_en": "AD certificates", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "ldapurl (Test)", "command": "ldapurl -H ldap://localhost 2>/dev/null || echo \"ldapurl: Install openldap\"", "description": "Тест LDAP URL", "description_en": "Test LDAP URL", "category": "Домен/LDAP", "interactive": True, "safe": True},
            {"name": "cat /etc/ldap.conf", "command": "cat /etc/ldap.conf 2>/dev/null || cat /etc/openldap/ldap.conf 2>/dev/null || echo \"LDAP config not found\"", "description": "LDAP конфигурация", "description_en": "LDAP configuration", "category": "Домен/LDAP", "interactive": True, "safe": True},
        ]
    }
}

# Категории для фильтрации (динамически обновляются)
CATEGORIES = ["Все", "Система", "Файлы", "Сеть", "Навигация", "Процессы", "Реестр", "Домен/LDAP", "Прочее"]
CATEGORIES_EN = ["All", "System", "Files", "Network", "Navigation", "Processes", "Registry", "Domain/LDAP", "Other"]

# Локализация интерфейса
LOCALIZATION = {
    "ru": {
        "title": "Terminal Commands Guide",
        "select_os": "Выберите операционную систему:",
        "search": "Поиск команд...",
        "category": "Категория:",
        "copy": "Копировать",
        "run": "Выполнить",
        "run_warning": "Выполнение команды",
        "run_message": "Команда будет выполнена в терминале.\nРезультат появится в новом окне.",
        "run_result": "Результат выполнения",
        "copied": "Скопировано в буфер!",
        "back": "← Назад",
        "all_categories": "Все",
        "no_commands": "Команды не найдены",
        "windows": "Windows",
        "linux": "Linux",
        "macos": "macOS",
        "language": "🇷🇺 RU",
        "confirm_run": "Выполнить команду?",
        "cancel": "Отмена",
        "close": "Закрыть",
        "running": "Выполнение...",
        "error": "Ошибка"
    },
    "en": {
        "title": "Terminal Commands Guide",
        "select_os": "Select operating system:",
        "search": "Search commands...",
        "category": "Category:",
        "copy": "Copy",
        "run": "Run",
        "run_warning": "Command Execution",
        "run_message": "Command will be executed in terminal.\nResult will appear in new window.",
        "run_result": "Execution Result",
        "copied": "Copied to clipboard!",
        "back": "← Back",
        "all_categories": "All",
        "no_commands": "No commands found",
        "windows": "Windows",
        "linux": "Linux",
        "macos": "macOS",
        "language": "🇬🇧 EN",
        "confirm_run": "Execute command?",
        "cancel": "Cancel",
        "close": "Close",
        "running": "Running...",
        "error": "Error"
    }
}
